#当发生文件修改时，网站重新生成 default：false
auto: true
#markdown: rdiscount

#代码高亮方式 pygments
#highlighter: 'pygments'

#分页功能
#paginate: 8
permalink: /:title

title: ··徐泽华的个人博客··
url: http://lychhh.github.io
#feed: /atom.xml
author_info: <a href="http://lychhh.github.io/">lyc</a>
baseurl: ""
author: XuZehua # add your name
author-img: ff.jpg # add your photo
github: lychhh # add your Github handle
about-author: I am a new JavaWeb developer. # add description
